query GetContentsByTagId($id: Int!, $offset: Int = 0, $limit: Int = 5) {
  content(where: {tags: {tag_id: {_eq: $id}}}, order_by: {createdAt: desc}, offset: $offset, limit: $limit) {
    id
    createdAt
    icon
    author {
      firstName
    }
    image
    isMenu
    isPublished
    type
    updatedAt
    participants {
      child {
        firstName
      }
      childId
    }
    translations {
      title
      content
      language
      slug
    }
    tags {
      tag {
        id
        translations {
          title
          language
        }
      }
    }
  }
}
