query getContentById($id: Int!) {
  content_by_pk(id: $id) {
    createdAt
    id
    image
    icon
    type
    isPublished
    isMenu
    tags {
    	tag {
        id
        translations {
          title
          language
        }
      }
    }
    updatedAt
    translations {
      content
      language
      slug
      title
    }
  }
}
