query GetContentsFrontPage($type: String = "article", $offset: Int = 0, $limit: Int = 10) {
  content(where: {type: {_eq: $type}, isPublished: {_eq: true}}, order_by: {createdAt: desc}, offset: $offset, limit: $limit) {
    id
    createdAt
    icon
    author {
      firstName
    }
    image
    caption
    isMenu
    isPublished
    type
    updatedAt
    translations {
      title
      content
      language
      slug
    }
    tags {
      tag {
        id
        translations {
          title
          language
        }
      }
    }
  }
}
