query getContentById($id: Int!, $isAdmin: Boolean = false) {
  content_by_pk(id: $id) {
    createdAt
    id
    image
    icon
    type
    isPublished
    isMenu
    price
    spots
    link
    participants {
      child {
        firstName
        lastName  @include(if: $isAdmin)
        birthDate @include(if: $isAdmin)
      }
      childId
    }
    tags {
    	tag {
        id
        translations {
          title
          slug
          language
        }
      }
    }
    updatedAt
    translations {
      content
      language
      slug
      title
    }
  }
}
