query getMenuItems {
  content(where: {isMenu: {_eq: true}, isPublished: {_eq: true}}) {
    id
    isMenu
    isPublished
    image
    icon
    type
    createdAt
    updatedAt
    translations {
      parentId
      slug
      title
      content
      language
    }
  }
}
