query getServicesByType($typeId: Int!) {
  services(where: {typeId: {_eq: $typeId}}) {
    createdAt
    description
    id
    isAvailable
    name
    periodicity
    price
    updatedAt
    image
    type {
      description
      icon
      name
      id
    }
  }
}
