query getServiceById($id: Int!) {
  services_by_pk(id: $id) {
    name
    description
    typeId
    periodicity
    price
    isAvailable
    id
    image
    spots
    participants {
      childId
    }
    createdAt
    updatedAt
    type {
      name
      id
    }
  }
}
