mutation insertPage($page: pages_insert_input = {}) {
  insert_pages_one(object: $page) {
    id
    createdAt
    updatedAt
    status
    image
    translations {
      parentId
      content
      title
      slug
      language
    }
  }
}
