mutation upsertPage($page: pages_insert_input!, $translations: [pages_translations_insert_input!] = {}) {
  insert_pages_one(object: $page, on_conflict: {constraint: pages_pkey, update_columns: [status, image, createdAt]}) {
    id
    createdAt
    updatedAt
    status
    image
  }
  insert_pages_translations(objects: $translations, on_conflict: {constraint: pages_translations_pkey, update_columns: [title, content]}) {
    returning {
      title
      content
      slug
      language
    }
  }
}
