export default {
  admin: {
    users: 'Gestión de usuarios'
  },
  errorNetwork: 'No tienes conexión a internet',
  extraescolars: 'Extraescolares',
  firebaseui: {
    google: 'Entra o regístrate con Google',
    email: 'Entra o regístrate con Email',
    phone: 'Entra o regístrate con teléfono'
  },
  forms: {
    autogeneratedField: 'Este campo se genera automáticamente',
    putChildrenLastName: 'Pon los apellidos de tu hijo/a. P.e. Sanchis Verdú',
    required: 'Este campo es necesario',
    save: 'Guardar',
    savedOk: 'Se ha guardado correctamente',
    selectFamily: 'Selecciona tu familia',
    selectFamilyMore: 'Elije una opción y pulsa OK',
    selectFamilyNew: 'Crea una familia nueva',
    validDate: 'Usa el seleccionador de fechas o escribe en formato YYYY/MM/DD',
    validEmail: 'Por favor, introduce una dirección de correo electrónico válida',
    validNif: 'Por favor, introduce un NIF o NIE válido',
    validPhone: 'Por favor, introduce un teléfono válido'
  },
  home: 'Inicio',
  login: 'Entrar',
  logout: 'Salir',
  member: {
    birthDate: 'Fecha de nacimiento',
    children: 'Hijos/as',
    familyData: 'Datos familiares',
    familyName: 'Nombre de la familia',
    firstName: 'Nombre',
    lastName: 'Apellidos',
    email: 'Correo electrónico',
    phone: 'Teléfono'
  },
  menu: {
    YourData: 'TUS DATOS',
    AmpaServices: 'LOS SERVICIOS DEL AMPA'
  },
  newVersion: 'Nueva versión disponible. Actualice pulsando el botón',
  personalData: 'Datos personales',
  settings: 'Preferencias',
  settingsPage: {
    general: 'Preferencias generales',
    language: 'Idioma',
    notifications: 'Notificaciones'
  },
  update: 'ACTUALIZAR',
  updatedAt: 'Actualizado el {date}'
}
