export default {
  admin: {
    users: 'Gestión de usuarios',
    pages: 'Gestión de págines',
    services: 'Gestión de servicios',
    blog: 'Gestión del blog'
  },
  errorNetwork: 'No tienes conexión a internet',
  extraescolars: 'Extraescolares',
  family: {
    hasRequestedJoinNotice: 'Has enviado una solicitud para unirte a una familia. Recuerda a quien dió de alta la familia que entre a la app para autorizarte',
    putChildrenLastName: 'Pon los apellidos de tu hijo/a. P.e. Sanchis Verdú',
    requestJoinNoticeAbort: 'Cancela la solicitud',
    requestJoinNotice: 'Has recibido una solicitud de {email} para unirse a gestionar tu familia',
    requestJoinNoticeAccept: 'Aceptar',
    requestJoinNoticeDecline: 'Rechazar'
  },
  firebaseui: {
    google: 'Entra o regístrate con Google',
    email: 'Entra o regístrate con Email',
    phone: 'Entra o regístrate con teléfono'
  },
  forms: {
    autogeneratedField: 'Este campo se genera automáticamente',
    ibanNotice: 'Facilitando mi número de cuenta AUTORIZO al AMPA para que, conforme a la ley de servicios de pago 16/2009, y con carácter indefinido mientras dure mi situación de asociado a la misma, giren en mi cuenta bancaria, los cargos derivados de mi pertenencia al AMPA así como de los servicios que contrate. Del mismo modo, me doy por enterado que los gastos por devolución de un recibo serán de 4 € y que deberé comunicar el cambio de cuenta bancaria o mi baja en la asociación.',
    required: 'Este campo es necesario',
    save: 'Guardar',
    savedOk: 'Se ha guardado correctamente',
    selectFamily: 'Selecciona tu familia',
    selectFamilyMore: 'Elije una opción y pulsa OK',
    selectFamilyNew: 'Crea una familia nueva',
    validDate: 'Usa el seleccionador de fechas o escribe en formato YYYY/MM/DD',
    validEmail: 'Por favor, introduce una dirección de correo electrónico válida',
    validIBAN: 'Per favor, introduce un IBAN válido',
    validNif: 'Por favor, introduce un NIF o NIE válido',
    validPhone: 'Por favor, introduce un teléfono válido'
  },
  home: 'Inicio',
  login: 'Entrar',
  logout: 'Salir',
  member: {
    birthDate: 'Fecha de nacimiento',
    children: 'Hijos/as',
    familyData: 'Datos familiares',
    familyDataNotice: 'Facilita primero los datos familiares',
    familyDataNoticeBtn: 'Ir a Datos Familiares',
    familyName: 'Nombre de la familia',
    firstName: 'Nombre',
    lastName: 'Apellidos',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    paymentData: 'Datos de domiciliación',
    userDataNotice: 'Cumplimenta primero los datos personales',
    userDataNoticeBtn: 'Ir a Datos Personales'
  },
  menu: {
    YourData: 'TUS DATOS',
    AmpaServices: 'LOS SERVICIOS DEL AMPA'
  },
  newVersion: 'Nueva versión disponible. Actualice pulsando el botón',
  personalData: 'Datos personales',
  settings: 'Preferencias',
  settingsPage: {
    general: 'Preferencias generales',
    language: 'Idioma',
    notifications: 'Notificaciones'
  },
  update: 'ACTUALIZAR',
  updatedAt: 'Actualizado el {date}',
  status: {
    PUBLISHED: 'PUBLICADO',
    DRAFT: 'BORRADOR'
  },
  table: {
    date: 'Fecha',
    title: 'Título',
    search: 'Buscar',
    status: 'Estado'
  }
}
