export default {
  admin: {
    users: 'Gestió d\'usuaris'
  },
  errorNetwork: 'No tens connexió a internet',
  extraescolars: 'Extraescolars',
  family: {
    hasRequestedJoinNotice: 'Has enviat una sol·licitud per a unir-te a una família. Recorda a qui va crear la família que entre a la app per a acceptar-te',
    putChildrenLastName: 'Poseu els cognoms del vostre fill/a. P.e. Sanchis Verdú',
    requestJoinNotice: 'Has rebut una sol·licitud de {email} per unir-se a gestionar la teua família',
    requestJoinNoticeAbort: 'Cancel·la la sol·licitud',
    requestJoinNoticeAccept: 'Accepta',
    requestJoinNoticeDecline: 'Rebutja'
  },
  firebaseui: {
    google: 'Entra o registra\'t amb Google',
    email: 'Entra o registra\'t amb Email',
    phone: 'Entra o registra\'t amb telèfon'
  },
  forms: {
    autogeneratedField: 'Aquest camp es genera automàticament',
    required: 'Aquest camp és necessari',
    save: 'Desa',
    savedOk: 'Desat correctament',
    selectFamily: 'Selecciona la teua família',
    selectFamilyMore: 'Trieu una opció i polseu d\'acord',
    selectFamilyNew: 'Crea una família nova',
    validDate: 'Usa el seleccionador de dates o introdueix-la en format YYYY/MM/DD',
    validEmail: 'Per favor, poseu una adreça electrònica vàlida',
    validNif: 'Per favor, poseu un NIF o NIE vàlid',
    validPhone: 'Per favor, poseu un telèfon vàlid'
  },
  home: 'Inici',
  login: 'Entrar',
  logout: 'Eixir',
  member: {
    birthDate: 'Data de naixement',
    children: 'Fills/es',
    familyData: 'Dades familiars',
    familyDataNotice: 'Omple primer les dades familiars',
    familyDataNoticeBtn: 'Aneu a Dades Familiars',
    familyName: 'Nom de la família',
    firstName: 'Nom',
    lastName: 'Cognoms',
    email: 'Correu electrònic',
    phone: 'Telèfon',
    paymentData: 'Dades de domiciliació'
  },
  menu: {
    YourData: 'LES TEUES DADES',
    AmpaServices: 'ELS SERVEIS DE L\'AMPA'
  },
  newVersion: 'Nova versió disponible. Actualitza polsant el botó',
  personalData: 'Dades personals',
  settings: 'Preferències',
  settingsPage: {
    general: 'Preferències generals',
    language: 'Idioma',
    notifications: 'Notificacions'
  },
  update: 'ACTUALITZA',
  updatedAt: 'Actualitzat el {date}'
}
