export default {
  admin: {
    users: 'Gestió d\'usuaris',
    pages: 'Gestió de pàgines',
    services: 'Gestió de serveis',
    family: 'Gestió de famílies',
    blog: 'Gestió del blog',
    tags: 'Gestió d\'etiquetes'
  },
  backToHome: 'Torna a la pàgina principal',
  content: {
    addImage: 'Afegeix una imatge de portada',
    content: 'Contingut',
    delete: 'Esborra',
    draft: 'Esborrany',
    isMenu: 'Incloure al menú',
    placeholder: 'Escriu alguna cosa ací...',
    publishOrSave: 'L\'article es troba en estat esborrany. Voleu només desar-lo o desar-lo i publicar-lo?',
    published: 'Publicat',
    save: 'Desa',
    see: 'Visualitza',
    title: 'Títol',
    type: {
      article: 'Article',
      page: 'Pàgina',
      service: 'Servei',
      title: 'Tipus'
    }
  },
  ca: 'Valencià',
  contact: {
    email: 'Correu electrònic',
    firstName: 'Nom',
    lastName: 'Cognoms',
    message: 'Missatge',
    messageSent: 'Missatge enviat correctament',
    phone: 'Telèfon',
    subject: 'Assumpte',
    title: 'Contacte'
  },
  error: {
    404: 'No hem trobat el que buscaves'
  },
  errorNetwork: 'No tens connexió a internet',
  es: 'Castellano',
  extraescolars: 'Extraescolars',
  family: {
    hasRequestedJoinNotice: 'Has enviat una sol·licitud per a unir-te a una família. Recorda a qui va crear la família que entre a la app per a acceptar-te',
    hiredServices: 'Serveis contractats per a {name}',
    putChildrenLastName: 'Poseu els cognoms del vostre fill/a. P.e. Sanchis Verdú',
    requestJoinNotice: 'Has rebut una sol·licitud de {email} per unir-se a gestionar la teua família',
    requestJoinNoticeAbort: 'Cancel·la la sol·licitud',
    requestJoinNoticeAccept: 'Accepta',
    requestJoinNoticeDecline: 'Rebutja'
  },
  firebaseui: {
    google: 'Entra o registra\'t amb Google',
    email: 'Entra o registra\'t amb Email',
    phone: 'Entra o registra\'t amb telèfon'
  },
  forms: {
    autogeneratedField: 'Aquest camp es genera automàticament',
    ibanNotice: 'Molt bé! Ja teniu una ordre de domiciliació en vigor. Useu el següent botó només en cas de canviar de compte.',
    mandateSigned: 'El manament de domiciliació s\'ha signat correctament',
    needNewMandate: 'Aquest enllaç de signatura ha caducat o no és vàlid. Genera un nou manament usant el botó.',
    required: 'Aquest camp és necessari',
    save: 'Desa',
    savedOk: 'Desat correctament',
    selectFamily: 'Selecciona la teua família',
    selectFamilyMore: 'Trieu una opció i polseu d\'acord',
    selectFamilyNew: 'Crea una família nova',
    send: 'Envia',
    sendMandate: 'Genera un nou manament de domiciliació',
    sendMandateMessage: 'En uns minuts rebràs el manament de domiciliació al correu {email} amb un enllaç per signar-lo. revisa també la safata de correu brossa',
    validDate: 'Usa el seleccionador de dates o introdueix-la en format YYYY/MM/DD',
    validEmail: 'Per favor, poseu una adreça electrònica vàlida',
    validIBAN: 'Per favor, poseu un IBAN vàlid',
    validNif: 'Per favor, poseu un NIF o NIE vàlid',
    validPhone: 'Per favor, poseu un telèfon vàlid'
  },
  home: 'Inici',
  login: 'Entrar',
  logout: 'Eixir',
  member: {
    addAdmin: 'Fer admin',
    birthDate: 'Data de naixement',
    children: 'Fills/es',
    familyData: 'Dades familiars',
    familyDataNotice: 'Omple primer les dades familiars',
    familyDataNoticeBtn: 'Aneu a Dades Familiars',
    familyName: 'Nom de la família',
    firstName: 'Nom',
    lastName: 'Cognoms',
    email: 'Correu electrònic',
    phone: 'Telèfon',
    removeAdmin: 'Llevar admin',
    needLogin: 'Necessites estar identificat per poder prosseguir',
    needPayment: 'Necessites omplir les dades de domiciliació per poder prosseguir',
    paymentData: 'Dades de domiciliació',
    userDataNotice: 'Omple primer les dades personals',
    userDataNoticeBtn: 'Aneu a Dades Personals'
  },
  menu: {
    AmpaServices: 'ELS SERVEIS DE L\'AMPA',
    contact: 'Contacte',
    featured: 'DESTACAT',
    YourData: 'LES TEUES DADES'
  },
  newVersion: 'Nova versió disponible. Actualitza polsant el botó',
  notification: {
    close: 'Tanca',
    read: 'Llegeix'
  },
  personalData: 'Dades personals',
  privacy: {
    title: 'Política de privadesa',
    content: `
    <p>Totes les dades que faciliteu en aquesta web són necessaries per a la comunicació i prestació de serveis i són custodiades per l'AMPA, els detalls socials de la qual podeu consultar a l'apartat <strong>Sobre Nosaltres</strong>.</p>
    <p>Aquest lloc fa ús de <em>cookies</em> pròpies i de tercers per millorar l'experiència d'usuari, així com per recollir dades sobre ús, per tal de millorar-la.</p>
    <p>Podeu exercir els vostres drets d'accés, rectificació i cancel·lació mitjançant el formulari de contacte.</p> 
    `
  },
  settings: {
    title: 'Preferències',
    email: 'Rebre comunicacions per email',
    general: 'Preferències generals',
    language: 'Idioma',
    notifications: 'Notificacions',
    push: {
      title: 'Notificacions push',
      deviceSpecific: 'Activa aquesta opció en cada dispositiu on hi vulgues rebre notificacions push'
    }
  },
  status: {
    PUBLISHED: 'PUBLICAT',
    DRAFT: 'ESBORRANY'
  },
  update: 'ACTUALITZA',
  updatedAt: 'Actualitzat el {date}',
  remove: {
    title: 'Eliminar',
    question: 'Esteu segur que voleu eliminar això?',
    confirm: 'Eliminat correctament'
  },
  service: {
    edit: {
      availability: 'Disponibilitat',
      description: 'Descripció',
      image: 'Imatge',
      join: 'Apuntar a {name}',
      name: 'Nom del servei',
      noParticipants: 'Encara no hi ha inscrits',
      participants: 'Actualment inscrits',
      periodicity: 'Periodicitat',
      price: 'Preu',
      remove: 'Esborra a {name}',
      spots: 'Capacitat',
      title: 'Edita un servei'
    },
    type: {
      description: 'Descripció',
      edit: 'Edita un tipus de servei',
      icon: 'Icona',
      iconPre: 'Poseu el nom de la classe de la icona, per exemple "las la-school". Les icones disponibles les podeu trobar a:',
      iconHint: 'Per exemple "las la-school"',
      name: 'Nom'
    }
  },
  table: {
    article: 'Articles',
    date: 'Data',
    families: 'Famílies',
    firstName: 'Nom',
    lastName: 'Cognoms',
    members: 'Membres',
    page: 'Pàgines',
    title: 'Títol',
    remesa: 'Genera remesa',
    search: 'Cerca',
    sendMessage: 'Envia un missatge',
    service: 'Serveis',
    serviceTypes: 'Tipus de serveis',
    showWithIban: 'Mostra els amb IBAN',
    showWithoutIban: 'Mostra els sense IBAN',
    status: 'Estat',
    tag: 'Etiquetes',
    type: 'Tipus'
  },
  tag: {
    add: 'Afegeix etiquetes',
    edit: 'Edita una etiqueta'
  },
  terms: {
    title: 'Condicions del servei',
    content: `
    <p>Mitjançant l'ús d'aquesta aplicació entenem que estàs d'acord en rebre informació sobre l'AMPA així com a formar part d'ella de manera activa, facilitant les teues dades reals i actualitzades.</p>
    <p>L'AMPA és una organització sense afany de lucre que es financia mitjançant les quotes dels seus afiliats i els serveis que ofereix poden ser subcontractats, i poden ser retirats o substituïts sense previ avís.</p>
    `
  }
}
