export default {
  admin: {
    users: 'Gestió d\'usuaris',
    pages: 'Gestió de pàgines',
    services: 'Gestió de serveis',
    blog: 'Gestió del blog',
    tags: 'Gestió d\'etiquetes'
  },
  content: {
    content: 'Contingut',
    draft: 'Esborrany',
    isMenu: 'Incloure al menú',
    published: 'Publicat',
    title: 'Títol',
    type: {
      article: 'Article',
      page: 'Pàgina',
      service: 'Servei',
      title: 'Tipus'
    }
  },
  ca: 'Valencià',
  contact: {
    email: 'Correu electrònic',
    firstName: 'Nom',
    lastName: 'Cognoms',
    message: 'Missatge',
    messageSent: 'Missatge enviat correctament',
    phone: 'Telèfon',
    subject: 'Assumpte',
    title: 'Contacte'
  },
  errorNetwork: 'No tens connexió a internet',
  es: 'Castellano',
  extraescolars: 'Extraescolars',
  family: {
    hasRequestedJoinNotice: 'Has enviat una sol·licitud per a unir-te a una família. Recorda a qui va crear la família que entre a la app per a acceptar-te',
    hiredServices: 'Serveis contractats per a {name}',
    putChildrenLastName: 'Poseu els cognoms del vostre fill/a. P.e. Sanchis Verdú',
    requestJoinNotice: 'Has rebut una sol·licitud de {email} per unir-se a gestionar la teua família',
    requestJoinNoticeAbort: 'Cancel·la la sol·licitud',
    requestJoinNoticeAccept: 'Accepta',
    requestJoinNoticeDecline: 'Rebutja'
  },
  firebaseui: {
    google: 'Entra o registra\'t amb Google',
    email: 'Entra o registra\'t amb Email',
    phone: 'Entra o registra\'t amb telèfon'
  },
  forms: {
    autogeneratedField: 'Aquest camp es genera automàticament',
    ibanNotice: 'Facilitant el meu número de compte AUTORITZE a l\'AMPA perquè, d\'acord amb la llei de serveis de pagament 16/2009, i amb caràcter indefinit mentre duri la meva situació d\'associat a la mateixa, giren al meu compte bancari, els càrrecs derivats de la meva pertinença a l\'AMPA així com dels serveis que contracti. De la mateixa manera, em dono per assabentat que les despeses per devolució d\'un rebut correran al meu càrrec i que hauré de comunicar el canvi de compte bancari o la meva baixa a l\'associació.',
    required: 'Aquest camp és necessari',
    save: 'Desa',
    savedOk: 'Desat correctament',
    selectFamily: 'Selecciona la teua família',
    selectFamilyMore: 'Trieu una opció i polseu d\'acord',
    selectFamilyNew: 'Crea una família nova',
    validDate: 'Usa el seleccionador de dates o introdueix-la en format YYYY/MM/DD',
    validEmail: 'Per favor, poseu una adreça electrònica vàlida',
    validIBAN: 'Per favor, poseu un IBAN vàlid',
    validNif: 'Per favor, poseu un NIF o NIE vàlid',
    validPhone: 'Per favor, poseu un telèfon vàlid'
  },
  home: 'Inici',
  login: 'Entrar',
  logout: 'Eixir',
  member: {
    addAdmin: 'Fer admin',
    birthDate: 'Data de naixement',
    children: 'Fills/es',
    familyData: 'Dades familiars',
    familyDataNotice: 'Omple primer les dades familiars',
    familyDataNoticeBtn: 'Aneu a Dades Familiars',
    familyName: 'Nom de la família',
    firstName: 'Nom',
    lastName: 'Cognoms',
    email: 'Correu electrònic',
    phone: 'Telèfon',
    removeAdmin: 'Llevar admin',
    needLogin: 'Necessites estar identificat per poder prosseguir',
    needPayment: 'Necessites omplir les dades de domiciliació per poder prosseguir',
    paymentData: 'Dades de domiciliació',
    userDataNotice: 'Omple primer les dades personals',
    userDataNoticeBtn: 'Aneu a Dades Personals'
  },
  menu: {
    AmpaServices: 'ELS SERVEIS DE L\'AMPA',
    contact: 'Contacte',
    featured: 'DESTACAT',
    YourData: 'LES TEUES DADES'
  },
  newVersion: 'Nova versió disponible. Actualitza polsant el botó',
  personalData: 'Dades personals',
  settings: 'Preferències',
  settingsPage: {
    general: 'Preferències generals',
    language: 'Idioma',
    notifications: 'Notificacions'
  },
  status: {
    PUBLISHED: 'PUBLICAT',
    DRAFT: 'ESBORRANY'
  },
  update: 'ACTUALITZA',
  updatedAt: 'Actualitzat el {date}',
  remove: {
    title: 'Eliminar',
    question: 'Esteu segur que voleu eliminar això?',
    confirm: 'Eliminat correctament'
  },
  service: {
    edit: {
      availability: 'Disponibilitat',
      description: 'Descripció',
      image: 'Imatge',
      join: 'Apuntar a {name}',
      name: 'Nom del servei',
      participants: 'Actualment inscrits',
      periodicity: 'Periodicitat',
      price: 'Preu',
      remove: 'Esborrar a {name}',
      spots: 'Capacitat',
      title: 'Edita un servei'
    },
    type: {
      description: 'Descripció',
      edit: 'Edita un tipus de servei',
      icon: 'Icona',
      iconPre: 'Poseu el nom de la classe de la icona, per exemple "las la-school". Les icones disponibles les podeu trobar a:',
      iconHint: 'Per exemple "las la-school"',
      name: 'Nom'
    }
  },
  table: {
    article: 'Articles',
    date: 'Data',
    firstName: 'Nom',
    lastName: 'Cognoms',
    members: 'Membres',
    page: 'Pàgines',
    title: 'Títol',
    search: 'Cerca',
    service: 'Serveis',
    serviceTypes: 'Tipus de serveis',
    status: 'Estat',
    tag: 'Etiquetes',
    type: 'Tipus'
  },
  tag: {
    add: 'Afegeix etiquetes',
    edit: 'Edita una etiqueta'
  }
}
