query memberById($id: String!) {
  members_by_pk(id: $id) {
    id
    firstName
    lastName
    email
    phone
    nif
    familyId
    hasRequestedJoinFamily
    joinFamilyRequest
    isAdmin
    canEmail
    createdAt
    family {
      id
      name
      iban
      children {
        id
        firstName
        lastName
        birthDate
        familyId
        hiredServices {
          service {
            type
            translations {
              language
              slug
              title
            }
            id
          }
        }
      }
    }
    messages {
      message {
        content
        createdAt
        id
        title
        status {
          read
        }
      }
    }
  }
}