query memberById($id: String!) {
  members_by_pk(id: $id) {
    id
    firstName
    lastName
    email
    phone
    family {
      id
      name
      children {
        id
        firstName
        lastName
        birthYear
      }
    }
  }
}