mutation updateMember(
  $id: String!,
  $member: members_set_input,
  ) {
  update_members_by_pk(
    pk_columns: {id: $id},
    _set: $member
  ) {
    id
    firstName
    lastName
    email
    phone
    nif
    familyId
    hasRequestedJoinFamily
    joinFamilyRequest
    isAdmin
    canEmail
    family {
      id
      name
      iban
      children {
        id
        firstName
        lastName
        birthDate
        familyId
        hiredServices {
          service {
            type
            translations {
              language
              slug
              title
            }
            id
          }
        }
      }
    }
  }
}
