mutation updateMember(
  $id: String!,
  $member: members_set_input,
  ) {
  update_members_by_pk(
    pk_columns: {id: $id},
    _set: $member
  ) {
    email,
    firstName,
    lastName,
    phone,
    nif
  }
}
