<template>
  <q-page padding class="bg-grey-2">
    <h1 class="text-h4">{{$t('member.familyData')}}</h1>
    <div class="q-gutter-md" style="max-width: 300px" v-if="member">
      <q-form ref="mForm" @submit.prevent="submitForm">
        <q-input outlined v-model="familyName" :label="$t('member.familyName')" bottom-slots disable>
          <template v-slot:hint>
            {{$t('forms.autogeneratedField')}}
          </template>
        </q-input>
        <h2 class="text-h4">
          {{$t('member.children')}}
          <q-btn class="float-right" color="primary" flat label="+ Afegeix" @click="addChild" />
        </h2>
        <div v-for="child in children" :key="child.id">
          <q-input outlined v-model="child.firstName" :label="$t('member.firstName')" :rules="[val => !!val || $t('forms.required')]" />
          <q-input outlined v-model="child.lastName" :label="$t('member.lastName')" :rules="[val => !!val || $t('forms.required')]" />
          <q-input outlined v-model="child.birthDate" mask="date" :rules="[val => datePattern.test(val) || $t('forms.validDate'), val => !!val || $t('forms.required')]" :label="$t('member.birthDate')">
            <template v-slot:append>
              <q-icon name="event" class="cursor-pointer">
                <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
                  <q-date v-model="child.birthDate">
                    <div class="row items-center justify-end">
                      <q-btn v-close-popup label="Close" color="primary" flat />
                    </div>
                  </q-date>
                </q-popup-proxy>
              </q-icon>
            </template>
          </q-input>
          <br>
          <q-separator/>
          <br>
        </div>
        <q-btn :disable="children.length === 0" color="primary" :label="$t('forms.save')" type="submit" />
      </q-form>
    </div>
  </q-page>
</template>

<script lang="ts">
// import { date } from 'quasar'
import { useRoute } from 'vue-router'
import { MembersService } from 'src/services/members'
import { computed, ref, watchEffect, onMounted } from 'vue'
import firebase from 'firebase/app'
import 'firebase/auth'
import { Child } from '@/models/Child'
import type { QForm } from 'quasar'

export default {
  name: 'PagePersonalData',
  setup () {
    const children = ref<Child[]>([])

    const familyName = computed(() => children.value[0]?.lastName)

    const mForm = ref<QForm>()

    const currentUserId = computed(() => {
      return firebase.auth().currentUser?.uid
    })

    const membersService = new MembersService()
    const route = useRoute()
    const id = computed(() => {
      const params = route.params?.id?.toString()
      if (params) {
        return params
      } else {
        return currentUserId.value || ''
      }
    })

    const result = membersService.getById(id.value)
    const member = result.data.value?.members_by_pk

    watchEffect(() => {
      children.value = member?.family?.children || []
    })

    const datePattern = /^-?[\d]+\/[0-1]\d\/[0-3]\d$/

    const addChild = () => {
      const child: Child = {
        firstName: '',
        lastName: '',
        birthDate: ''
      }
      children.value.push(child)
    }

    onMounted(() => console.log('mForm', mForm.value))

    // // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    // const formIsValid = async () => {
    //   const thereAreChildren = children.value.length > 0
    //   console.log('thereAreChildren', thereAreChildren)
    //   const noErrors = await memberForm.value?.validate()
    //   console.log('noErrors', noErrors)
    //   return thereAreChildren && noErrors
    // }

    const submitForm = async (): Promise<void> => {
      console.log('submit clicked')
      return mForm.value?.validate().then(success => {
        if (success) {
        // yay, models are correct
          console.log('success')
        } else {
        // oh no, user has filled in
        // at least one invalid value
          console.log('no valid')
        }
      })
    }

    return {
      member,
      familyName,
      children,
      addChild,
      datePattern,
      submitForm
    }
  }
}
</script>
