query getArticles($offset: Int, $limit: Int) {
    articles(offset: $offset, limit: $limit, order_by: {created_at: desc}) {
    id
    status
    image
    created_at
    updated_at
        translations {
            title
            slug
            language
        }
    }
}