query getArticles($offset: Int, $limit: Int) {
    articles(offset: $offset, limit: $limit, order_by: {createdAt: desc}) {
    id
    status
    image
    createdAt
    updatedAt
        translations {
            title
            slug
            language
        }
    }
}