query getArticles($filter: String = "%%", $limit: Int, $offset: Int, $orderBy: [articles_order_by!] = {createdAt: desc}) {
  articles_aggregate(
    where: {
      translations: 
        {
          _or: [
            {content: {_ilike: $filter}},
            {title: {_ilike: $filter}}
          ]
      	}
  	}
  ) {
    aggregate {
      count
    }
  }
  articles(order_by: $orderBy, limit: $limit, offset: $offset, 
    where: {
      translations: 
        {
          _or: [
            {content: {_ilike: $filter}},
            {title: {_ilike: $filter}}
          ]
      	}
  	}
  ) {
    author {
      firstName
    }
    createdAt
    id
    image
    status
    updatedAt
    translations {
      slug
      language
      title
      content
    }
  }
}
