query getServiceTypes($filter: String = "%%", $limit: Int, $offset: Int, $orderBy: [service_types_order_by!] = {createdAt: desc}) {
  service_types_aggregate(
    where: {
      _or: [
        {name: {_ilike: $filter}},
        {description: {_ilike: $filter}}
      ]
    },
    limit: $limit,
    offset: $offset) {
    aggregate {
      count
    }
  }
  service_types(
    where: {
      _or: [
        {name: {_ilike: $filter}},
        {description: {_ilike: $filter}}
      ]
    },
    limit: $limit,
    offset: $offset,
    order_by: $orderBy) {
    name
    description
    icon
    id
    createdAt
    updatedAt
  }
}
