query getServiceById($id: Int!) {
  services_by_pk(id: $id) {
    name
    description
    typeId
    periodicity
    price
    isAvailable
    id
    image
    spots
    participants {
      child {
        id
        firstName
        lastName
        birthDate
        familyId
      }
    }
    createdAt
    updatedAt
    type {
      name
      id
    }
  }
}
