query getServeisPerTipus($typeId: Int!, $limit: Int, $offset: Int, $orderBy: [services_order_by]= {createdAt: desc}, $filter: String = "%%") {
  services_aggregate(where: {
    typeId: {_eq: $typeId},
    _or: [
      {name: {_ilike: $filter}},
      {description: {_ilike: $filter}}
    ]
  },
    limit: $limit,
    offset: $offset) {
    aggregate {
      count
    }
  }
  services(where: {
    typeId: {_eq: $typeId},
    _or: [
      {name: {_ilike: $filter}},
      {description: {_ilike: $filter}}
    ]
  }, limit: $limit, offset: $offset, order_by: $orderBy) {
    id
    name
    periodicity
    isAvailable
    image
    description
    price
    spots
    updatedAt
    createdAt
  }
}